services:
  student-service:
    build: 
      context: ./studentservice
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - ELASTIC_APM_SERVER_URL=http://192.168.56.114:8200
      - ELASTIC_APM_SECRET_TOKEN=thO5a5ISLcoTrogIcH8XljEPRLs9uqoswl
      - ELASTIC_APM_SERVICE_NAME=student-service

  teacher-service:
    build: 
      context: ./teacherservice
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - ELASTIC_APM_SERVER_URL=http://192.168.56.114:8200
      - ELASTIC_APM_SECRET_TOKEN=thO5a5ISLcoTrogIcH8XljEPRLs9uqoswl
      - ELASTIC_APM_SERVICE_NAME=teacher-service

  employee-service:
    build: 
      context: ./employeeservice
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - ELASTIC_APM_SERVER_URL=http://192.168.56.114:8200
      - ELASTIC_APM_SECRET_TOKEN=thO5a5ISLcoTrogIcH8XljEPRLs9uqoswl
      - ELASTIC_APM_SERVICE_NAME=employee-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - ELASTIC_APM_SERVER_URL=http://192.168.56.114:8200
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: