apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  labels:
    app: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "kindergarten-role"
        vault.hashicorp.com/agent-inject-secret-mongodb: "kindergarten/config/mongodb"
        vault.hashicorp.com/agent-inject-template-mongodb: |
          {{- with secret "kindergarten/config/mongodb" -}}
          export MONGODB_URI="{{ .Data.data.uri }}"
          export MONGODB_USERNAME="{{ .Data.data.username }}"
          export MONGODB_PASSWORD="{{ .Data.data.password }}"
          export MONGODB_DATABASE="{{ .Data.data.database }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-ports: "kindergarten/config/ports"
        vault.hashicorp.com/agent-inject-template-ports: |
          {{- with secret "kindergarten/config/ports" -}}
          export SERVICE_PORT="{{ .Data.data.employee }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-services: "kindergarten/config/services"
        vault.hashicorp.com/agent-inject-template-services: |
          {{- with secret "kindergarten/config/services" -}}
          export SERVICE_NAME="{{ .Data.data.employee }}"
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: employee-service
        image: nanil0034/kindergarten-registry-employee:59
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30003
  type: NodePort