apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kindergarten-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: kindergarten-ingress 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /std(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: student-service
            port:
              number: 5001
      - path: /emp(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: employee-service
            port:
              number: 5003
      - path: /tech(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: teacher-service
            port:
              number: 5002