apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kindergarten-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: nasirtechtalks.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /std
        pathType: Prefix
        backend:
          service:
            name: student-service
            port:
              number: 5001
      - path: /emp
        pathType: Prefix
        backend:
          service:
            name: employee-service
            port:
              number: 5003
      - path: /tech
        pathType: Prefix
        backend:
          service:
            name: teacher-service
            port:
              number: 5002