apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kindergarten-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "192.168.56.10.nip.io"  # No host file needed!
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api/students
            pathType: Prefix
            backend:
              service:
                name: student-service
                port:
                  number: 5001
          - path: /api/teachers
            pathType: Prefix
            backend:
              service:
                name: teacher-service
                port:
                  number: 5002
          - path: /api/employees
            pathType: Prefix
            backend:
              service:
                name: employee-service
                port:
                  number: 5003