apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
    spec:
      containers:
      - name: teacher-service
        image: nanil0034/kindergarten-registry-teacher:19
        ports:
        - containerPort: 5002
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongodb-uri
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: database-name
        - name: ELASTIC_APM_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: elastic-apm-server-url
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: elastic-apm-secret-token
        - name: ELASTIC_APM_SERVICE_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: elastic-apm-service-name-teacher
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-service
spec:
  selector:
    app: teacher-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP