apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
    spec:
      serviceAccountName: vault-auth  # Same service account
      containers:
      - name: teacher-service
        image: nanil0034/kindergarten-registry-teacher:59
        ports:
        - containerPort: 5002
        env:
        # ভাউল্ট অ্যাড্রেস
        - name: VAULT_ADDR
          value: "http://192.168.121.132:8200"
        # Optional: Service account টোকেন মাউন্ট করুন
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
        # Health check
        livenessProbe:
          httpGet:
            path: /tech/health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /tech/health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: vault-token
        projected:
          sources:
          - serviceAccountToken:
              audience: vault
              expirationSeconds: 7200
              path: token
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-service
spec:
  selector:
    app: teacher-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
  type: NodePort