aapiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "kindergarten-role"
        vault.hashicorp.com/agent-inject-secret-config: "kindergarten/data/config"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "kindergarten/data/config" -}}
          export MONGODB_URI="{{ .Data.data.mongodb-uri }}"
          export DATABASE_NAME="{{ .Data.data.database-name }}"
          export ELASTIC_APM_SERVER_URL="{{ .Data.data.elastic-apm-server-url }}"
          export ELASTIC_APM_SECRET_TOKEN="{{ .Data.data.elastic-apm-secret-token }}"
          export ELASTIC_APM_SERVICE_NAME="teacher-service"
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: teacher-service
        image: nanil0034/kindergarten-registry-teacher:58
        ports:
        - containerPort: 5002
        env:
        - name: ELASTIC_APM_SERVICE_NAME
          value: "teacher-service"
        command: ["/bin/sh"]
        args: ["-c", "source /vault/secrets/config && /app/teacher-service"]
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-service
spec:
  selector:
    app: teacher-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
  type: NodePort