apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service
  labels:
    app: teacher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
    spec:
      containers:
      - name: teacher-service
        image: nanil0034/kindergarten-registry-teacher:84
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        # Vault Configuration - VAULT_TOKEN বাদ দিন কারণ Dockerfile এ embedded আছে
        - name: VAULT_ADDR
          value: "http://192.168.121.132:8200"
        - name: SERVICE_NAME
          value: "teacher"
        # VAULT_TOKEN env variable remove করুন
        # - name: VAULT_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: vault-tokens
        #       key: teacher-token
        # - name: VAULT_SKIP_VERIFY
        #   value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-service
spec:
  selector:
    app: teacher-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
  type: NodePort