apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-secrets
data:
  # এই values গুলো Vault থেকে dynamically replace হবে
  MONGODB_URI: "placeholder"
  DATABASE_NAME: "placeholder"
  ELASTIC_APM_SERVER_URL: "placeholder"
  ELASTIC_APM_SECRET_TOKEN: "placeholder"